"""
city_data.py
─────────────────────────────────────────────
Static zone / shelter / emergency-contact data for the 5 monitored cities.
"""

CITY_DATA = {
    'hyderabad': {
        'lat': 17.385, 'lon': 78.4867, 'name': 'Hyderabad',
        'zones': {
            'high': [
                'Dharavi Colony (Malakpet) — dense housing, flood-prone nala',
                'Nallakunta Slums — low-lying, poor drainage',
                'Musheerabad — overcrowded, fire risk',
                'Bholakpur — nala belt, flood zone',
                'Toli Chowki Nala Belt — annual flooding reported',
                'Uppuguda — waterlogging during heavy rain',
                'Chandrayangutta Low-lying Areas — flood-prone',
                'Amberpet Nala Zone — high structural vulnerability',
            ],
            'medium': [
                'Santoshnagar — moderate flood risk',
                'Dilsukhnagar Periphery — drainage issues',
                'Barkas — partially low-lying',
                'Uppal Kalan — nala proximity risk',
                'Malakpet Extension — medium density',
                'Katedan Industrial fringe — chemical fire risk',
            ],
            'low': [
                'Secunderabad North — good infrastructure',
                'Madhapur — planned zone, high elevation',
                'Gachibowli — modern drainage',
                'Jubilee Hills — elevated terrain',
                'Banjara Hills — good road access',
                'Kondapur — low flood risk',
            ],
        },
        'shelters': [
            {'name': 'GHMC Relief Centre — LB Nagar', 'address': 'Near LB Nagar Circle, Hyderabad', 'capacity': '500 persons', 'contact': '040-21111111'},
            {'name': 'Municipal School Shelter — Malakpet', 'address': 'Malakpet MCD School, Hyderabad', 'capacity': '300 persons', 'contact': '040-21222222'},
            {'name': 'GHMC Shelter — Musheerabad', 'address': 'Musheerabad Community Hall, Hyderabad', 'capacity': '400 persons', 'contact': '040-21333333'},
            {'name': 'Red Cross Centre — Nampally', 'address': 'Red Cross Bhavan, Nampally, Hyderabad', 'capacity': '600 persons', 'contact': '040-24731955'},
            {'name': 'SDRF Camp — Uppal Stadium', 'address': 'Uppal Stadium Grounds, Hyderabad', 'capacity': '800 persons', 'contact': '040-23456789'},
        ],
        'emergency': {'local': 'GHMC: 040-21111111', 'helpline': 'TSSDMA: 040-23454088'},
    },
    'delhi': {
        'lat': 28.6139, 'lon': 77.209, 'name': 'Delhi',
        'zones': {
            'high': [
                'Yamuna Khadar Slums — severe flood risk every monsoon',
                'Seemapuri — dense informal settlement, waterlogging',
                'Trilokpuri — fire risk, poor road access',
                'Kalyanpuri — drainage failure, flood zone',
                'Mustafabad — Yamuna floodplain proximity',
                'Seelampur — low-lying, annual flooding',
                'Bhalswa Jahangirpuri — landfill proximity, fire risk',
                'Savda Ghevra — resettlement colony, poor infrastructure',
            ],
            'medium': [
                'Shahdara East — moderate flood risk',
                'Gokulpuri — partial waterlogging',
                'Nand Nagri — drainage issues',
                'Laxmi Nagar Periphery — moderate density risk',
                'Babarpur — semi-formal housing',
                'Karawal Nagar — peri-urban risk',
            ],
            'low': [
                'Dwarka Sector 1-6 — planned, good drainage',
                'Rohini Sector 1 — modern infrastructure',
                'Saket — elevated, low flood risk',
                'Vasant Kunj — good road/drainage access',
                'Pitampura — organized colony',
                'Janakpuri — well-planned residential',
            ],
        },
        'shelters': [
            {'name': 'Delhi Govt Night Shelter — Yamuna Bank', 'address': 'Yamuna Bank Metro Station Area, Delhi', 'capacity': '700 persons', 'contact': '011-23392200'},
            {'name': 'DUSIB Shelter — Seemapuri', 'address': 'Seemapuri Ring Road, Delhi', 'capacity': '500 persons', 'contact': '011-22004488'},
            {'name': 'MCD Relief Camp — Trilokpuri', 'address': 'Block 20, Trilokpuri, East Delhi', 'capacity': '450 persons', 'contact': '011-23416969'},
            {'name': 'Red Cross Shelter — ITO', 'address': 'Red Cross Bhavan, ITO, Delhi', 'capacity': '800 persons', 'contact': '011-23711551'},
            {'name': 'Civil Defence Camp — Shahdara', 'address': 'Shahdara District HQ, Delhi', 'capacity': '600 persons', 'contact': '011-22323040'},
        ],
        'emergency': {'local': 'DDMA: 011-23392200', 'helpline': 'Delhi Disaster: 1077'},
    },
    'mumbai': {
        'lat': 19.076, 'lon': 72.8777, 'name': 'Mumbai',
        'zones': {
            'high': [
                "Dharavi — Asia's largest slum, severe flood & fire risk",
                'Kurla East Low-lying — annual waterlogging',
                'Govandi — poor drainage, chemical risk from Deonar',
                'Mankhurd — flood-prone, low elevation',
                'Malvani, Malad — coastal flooding risk',
                'Deonar — landfill fire risk, toxic flood water',
                'Shivajinagar, Govandi — dense informal housing',
                'Ambujwadi, Malad — hillside slum, landslide risk',
            ],
            'medium': [
                'Bhandup West Nala — partial flood zone',
                'Vikhroli East — drainage congestion',
                'Chembur Periphery — moderate flood risk',
                'Jogeshwari East — seasonal waterlogging',
                'Antop Hill — moderate density risk',
                'Ghatkopar East fringe — partial low-lying',
            ],
            'low': [
                'Bandra West — good elevation, drainage',
                'Andheri West — planned infrastructure',
                'Powai — hillside, good drainage',
                'Kandivali West — modern residential',
                'Goregaon West — organized colony',
                'Borivali West — elevated terrain',
            ],
        },
        'shelters': [
            {'name': 'BMC Shelter — Dharavi', 'address': 'Near Dharavi Main Road, Sion, Mumbai', 'capacity': '1000 persons', 'contact': '022-24132222'},
            {'name': 'MCGM Relief Centre — Kurla', 'address': 'Kurla Municipal School, Mumbai', 'capacity': '600 persons', 'contact': '022-25018000'},
            {'name': 'Red Cross Mumbai — Matunga', 'address': 'Red Cross Bhavan, Matunga, Mumbai', 'capacity': '700 persons', 'contact': '022-24014390'},
            {'name': 'NDRF Base Camp — Colaba', 'address': 'Colaba Causeway Area, Mumbai', 'capacity': 'Deploy-ready', 'contact': '022-22846740'},
            {'name': 'Cyclone Shelter — Malvani', 'address': 'Malvani Municipal Ground, Malad West', 'capacity': '900 persons', 'contact': '022-28814000'},
        ],
        'emergency': {'local': 'BMC: 1916', 'helpline': 'MCGM Disaster: 022-22694727'},
    },
    'chennai': {
        'lat': 13.0827, 'lon': 80.2707, 'name': 'Chennai',
        'zones': {
            'high': [
                'Buckingham Canal Belt — severe flood risk, poor drainage',
                'Vyasarpadi — low-lying, annual flooding',
                'Kolathur Low-lying — waterlogging during cyclones',
                'Tiruvottiyur — coastal, storm surge risk',
            ],
            'medium': [
                'Ambattur Industrial fringe — chemical risk',
                'Manali North — petrochemical proximity',
                'Madhavaram — moderate flood risk',
                'Perambur Periphery — drainage congestion',
                'Kodambakkam Nala — partial flood zone',
                'Tondiarpet East — medium density',
                'Royapuram Coastal — storm surge risk',
                'Thiruvanmiyur — coastal erosion risk',
            ],
            'low': [
                'Anna Nagar — planned, good drainage',
                'Adyar — elevated areas only',
                'Velachery (high ground) — partial risk only',
                'Nungambakkam — well-planned residential',
                'T Nagar — commercial, good infrastructure',
                'Guindy — industrial but organized',
                'Porur — good road/drainage access',
                'Sholinganallur — IT corridor, planned',
            ],
        },
        'shelters': [
            {'name': 'GCC Shelter — Vyasarpadi', 'address': 'Vyasarpadi School Grounds, Chennai', 'capacity': '600 persons', 'contact': '044-25384510'},
            {'name': 'Corporation Shelter — Kolathur', 'address': 'Kolathur Municipal Market, Chennai', 'capacity': '500 persons', 'contact': '044-25382222'},
            {'name': 'Red Cross Centre — Egmore', 'address': 'Red Cross Bhavan, Egmore, Chennai', 'capacity': '700 persons', 'contact': '044-28191616'},
            {'name': 'SDRF Camp — Tiruvottiyur', 'address': 'Tiruvottiyur Beach Road, Chennai', 'capacity': '800 persons', 'contact': '044-25342000'},
            {'name': 'Cyclone Centre — Marina Beach', 'address': 'Marina Beach Grounds, Chennai', 'capacity': '2000 persons', 'contact': '044-28543300'},
        ],
        'emergency': {'local': 'GCC: 1913', 'helpline': 'TNSDMA: 1070'},
    },
    'jammu': {
        'lat': 32.7266, 'lon': 74.857, 'name': 'Jammu & Kashmir',
        'zones': {
            'high': [
                'Tawi Riverbank Settlements — flash flood risk every monsoon',
                'Talab Tillo — low-lying, waterlogging',
                'Rajpura Slum — poor drainage, landslide proximity',
                'Gole Gujral — dense informal housing',
                'Gangyal Industrial Slums — fire and flood risk',
                'Rehari Colony Flood Zone — Tawi floodplain',
                'Barnai Nullah Area — annual flash flooding',
                'Old Jammu Walled City — structural vulnerability, fire risk',
            ],
            'medium': [
                'Bantalab — partial flood risk',
                'Sidhra — moderate landslide exposure',
                'Channi Himmat — hillside drainage issues',
                'Parade Ground Area — moderate density risk',
                'Bahu Fort fringe — landslide zone',
                'Paloura — riverside proximity',
            ],
            'low': [
                'Trikuta Nagar — planned colony, good drainage',
                'Gandhi Nagar — modern residential',
                'Bakshi Nagar — organized layout',
                'Shastri Nagar — good road access',
                'Nanak Nagar — elevated terrain',
                'Amphalla — planned area',
            ],
        },
        'shelters': [
            {'name': 'JMC Relief Camp — Talab Tillo', 'address': 'Talab Tillo Ground, Jammu', 'capacity': '500 persons', 'contact': '0191-2542424'},
            {'name': 'Govt Shelter — Rehari Colony', 'address': 'Rehari Colony Panchayat Ghar, Jammu', 'capacity': '300 persons', 'contact': '0191-2532100'},
            {'name': 'SDRF Centre — Gandhi Nagar', 'address': 'SDRF HQ Gandhi Nagar, Jammu', 'capacity': '600 persons', 'contact': '0191-2520044'},
            {'name': 'Red Cross Shelter — Jammu', 'address': 'Red Cross Bhavan, Residency Road, Jammu', 'capacity': '400 persons', 'contact': '0191-2543277'},
            {'name': 'Flood Relief Camp — Gangyal', 'address': 'Gangyal Industrial Area Ground, Jammu', 'capacity': '700 persons', 'contact': '0191-2500100'},
        ],
        'emergency': {'local': 'JMC: 0191-2542424', 'helpline': 'JKSDMA: 0194-2440691'},
    },
}